# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diag_quad_mat <- function(A, B) {
    .Call(`_bhetGP_diag_quad_mat`, A, B)
}

Exp2 <- function(distmat, tau2, theta, g) {
    .Call(`_bhetGP_Exp2`, distmat, tau2, theta, g)
}

Exp2vec <- function(distmat, tau2, theta, g) {
    .Call(`_bhetGP_Exp2vec`, distmat, tau2, theta, g)
}

Exp2Sep <- function(x1, x2, tau2, theta, g) {
    .Call(`_bhetGP_Exp2Sep`, x1, x2, tau2, theta, g)
}

Exp2SepVec <- function(x1, x2, tau2, theta, g) {
    .Call(`_bhetGP_Exp2SepVec`, x1, x2, tau2, theta, g)
}

Matern <- function(distmat, tau2, theta, g, v) {
    .Call(`_bhetGP_Matern`, distmat, tau2, theta, g, v)
}

MaternSep <- function(x1, x2, tau2, theta, g, v) {
    .Call(`_bhetGP_MaternSep`, x1, x2, tau2, theta, g, v)
}

MaternVec <- function(distmat, tau2, theta, g, v) {
    .Call(`_bhetGP_MaternVec`, distmat, tau2, theta, g, v)
}

MaternSepVec <- function(x1, x2, tau2, theta, g, v) {
    .Call(`_bhetGP_MaternSepVec`, x1, x2, tau2, theta, g, v)
}

MaternProdSep <- function(x1, x2, tau2, theta, g, v) {
    .Call(`_bhetGP_MaternProdSep`, x1, x2, tau2, theta, g, v)
}

MaternProdSepVec <- function(x1, x2, tau2, theta, g, v) {
    .Call(`_bhetGP_MaternProdSepVec`, x1, x2, tau2, theta, g, v)
}

forward_solve_raw <- function(U, z, NNarray) {
    .Call(`_bhetGP_forward_solve_raw`, U, z, NNarray)
}

rev_matrix <- function(x) {
    .Call(`_bhetGP_rev_matrix`, x)
}

U_entries_Hom <- function(Ncores, x, revNNarray, tau2, theta, g, v) {
    .Call(`_bhetGP_U_entries_Hom`, Ncores, x, revNNarray, tau2, theta, g, v)
}

U_entries <- function(Ncores, x, revNNarray, tau2, theta, g, v) {
    .Call(`_bhetGP_U_entries`, Ncores, x, revNNarray, tau2, theta, g, v)
}

U_entries_sep_Hom <- function(Ncores, x, revNNarray, tau2, theta, g, v) {
    .Call(`_bhetGP_U_entries_sep_Hom`, Ncores, x, revNNarray, tau2, theta, g, v)
}

U_entries_sep <- function(Ncores, x, revNNarray, tau2, theta, g, v) {
    .Call(`_bhetGP_U_entries_sep`, Ncores, x, revNNarray, tau2, theta, g, v)
}

check_omp <- function() {
    invisible(.Call(`_bhetGP_check_omp`))
}

check_cores <- function(Ncores) {
    .Call(`_bhetGP_check_cores`, Ncores)
}

row_col_pointers <- function(NNarray) {
    .Call(`_bhetGP_row_col_pointers`, NNarray)
}

